In [7]:
systems = [
        ('Pb', 'Pb', 2760),
        ('Au', 'Au', 200),
        #('Pb', 'Pb', 5020),
        #('Xe', 'Xe', 5440)
        ]
system_strs = ['{:s}-{:s}-{:d}'.format(*s) for s in systems]
num_systems = len(system_strs)

In [12]:
[print(*s) for s in systems]

Pb Pb 2760
Au Au 200


[None, None]

In [15]:
xx=[1,2,3,4,5]
ls=*xx

SyntaxError: can't use starred expression here (<ipython-input-15-8f23f2de8d46>, line 2)

In [1]:
import numpy as np

In [13]:
Data=np.fromfile('/Users/dananjayaliyanage/git/emulator-validation/design_pts/design_points_main_PbPb-2760.dat')

In [25]:
Data.size

8990

In [41]:
a=[1,2,3,4]
b=[1,2]
np.outer(a,b)

array([[1, 2],
       [2, 4],
       [3, 6],
       [4, 8]])

In [42]:
np.subtract.outer(a,b)

array([[ 0, -1],
       [ 1,  0],
       [ 2,  1],
       [ 3,  2]])

In [45]:
np.array(a)**2

array([ 1,  4,  9, 16])

In [51]:
X=np.array([1,2,3,4,5])
X[:]
L=[[1,2],[2,3],[3,3]]

In [52]:
for (idx, value) in L:
    X[:,idx] = value

IndexError: too many indices for array

In [66]:
ll=np.zeros(3)

In [77]:
~True

-2

TypeError: list expected at most 1 argument, got 3